cognitedata/cognite-sdk-python-experimental

cognite/experimental/_api/functions.py
tests/tests_unit/test_api/function_code/handler.py
tests/tests_unit/test_api/test_functions.py

This PR adds method `FunctionsAPI.create()` which can be used to create a function in two ways:
1) By using the `folder` argument which is the relative path to the folder containing the function source code (i.e. handler.py):
```
client = CogniteClient()
func = client.functions.create(name="myfunction", path="path/to/code")
```
2) By using the `file_id` argument if the source code is already uploaded to the files-API:
```
func = client.functions.create(name="myfunction", file_id=1234)
```
Arguments `name` and exactly one of `folder` or `file_id` are required. Optional arguments are: `external_id`, `description`, `owner`, `api_key`, `secrets`.
The method `client.functions.create()` returns an object of type `Function`:
```
{
"id": …
```

[CDF-3676] Add FunctionsAPI.create()

---

cognite/experimental/_api/functions.py
tests/tests_unit/test_api/test_functions.py

This PR adds `FunctionsAPI.delete()`. Accepted arguments are `id: Union[int, List[int]]` and `external_id: Union[str, List[str]]`, and the method is used as:
```
c.functions.delete(id=[1,2,3], external_id="function3")
```

[CDF-3677] Add FunctionsAPI.delete()

---

cognite/experimental/_api/functions.py
tests/tests_unit/test_api/test_functions.py

This PR adds methods `FunctionsAPI.retrieve()` and `FunctionsAPI.retrieve_multiple()`.
The first of these can retrieve a single function by either `id` or `external_id` (mutually exclusive):
```
func = c.functions.retrieve(id=1)
```
or
```
func = c.functions.retrieve(external_id="somefunc")
```
The second can retrieve multiple functions specified by keyword arguments `ids (list)` and/or `external_ids (list)`:
```
funcs = c.functions.retrieve_multiple(ids=[1, 2, 3], external_ids=["somefunc"])
```

[CDF-3675] Add FunctionsAPI.retrieve() and FunctionsAPI.retrieve_multiple()

---

cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
tests/tests_unit/test_api/test_functions.py

This PR adds `FunctionsAPI.call()`, which is used to call functions by `id` or `external_id`. It is used as follows:
```
call = c.functions.call(id=4172094376815850)
```
Where a `Completed` call looks like:
```
print(call)
{
"id": 4172094376815850,
"start_time": "2020-04-06 07:52:03",
"end_time": "2020-04-06 07:52:04",
"response": {
"assetId": 1234
},
"status": "Completed"
}
```
Alternatively, you can make the function call from a `Function` object directly:
```
func = c.functions.retrieve(id=4172094376815850)
call = func.call()
```
Optional arguments are `data`, which needs to be JSON serializable, and `asynchronous` (defaults to `False`) which lets you call the function asynchronously.

[CDF-3678] [CDF-3680] Add FunctionsAPI.call()

---

cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
tests/tests_unit/test_api/test_functions.py

This PR adds a new `FunctionCallsAPI` under `FunctionsAPI` and also implements the methods `FunctionCallsAPI.retrieve()` and `FunctionCallsAPI.list()`. They are used as follows:
```
call = c.functions.calls.retrieve(call_id=456, function_id=123)
calls = c.functions.calls.list(function_id=123)
```
where `call` and `calls` are objects of type `FunctionCall` and `FunctionCallList`, respectively. The keyword argument `function_id` can in both cases be replaced by `function_external_id`.
Function calls can also be retrieve/listed directly on a `Function` object:
```
func = c.functions.retrieve(id=123)
call = func.retrieve_call(call_id=456)
calls = func.list_calls()
```

[CDF-3767] Add FunctionCallsAPI.list() and FunctionCallsAPI.retrieve()

---

cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
tests/tests_unit/test_api/test_functions.py
tests/tests_unit/test_data_classes/test_functions.py

This PR adds the method `FunctionCallsAPI.logs()` which returns logs for a specific function call. It is used as follows:
```
logs = c.functions.calls.logs(call_id=456, function_id=123)
```
where the logs looks like:
````
print(logs)
[
{
"timestamp": "2020-04-07 17:03:08",
"message": "Started function execution"      
},
{
"timestamp": "2020-04-07 17:03:12",
"message": "Finished function execution"      
},
]
````
Optionally, the argument `function_id` can be replaced by `function_external_id`.
The logs can also be retrieved directly from a `FunctionCall` object, like so:
```
func = c.functions.create(name="myfunction", folder="path/to/code")
call = func.call()
logs = call.logs()
```

[CDF-3768] Add FunctionCallsAPI.logs()

---

CHANGELOG.md
cognite/experimental/_api/functions.py
tests/tests_unit/test_api/test_functions.py

This PR makes it possible to deploy a function from code. The function must be named `handle` and can have arguments that are a subset of `(data, client, secrets)`:
```
def handle(data):
return data["value"]*2
```
Then you create a function as follows:
```
func = c.functions.create(name="myfunc", function_handle=handle)
```

[CDF-3927] Allow function to be deployed from code

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

```
schedules = c.functions.schedules.list()
schedule = c.functions.schedules.create(name= "my-schedule",
function_external_id="user/hello-cognite/hello-cognite:latest",
cron_expression="*/5 * * * *", description="Hi")
c.functions.schedules.delete(id= 123)
my_function = c.functions.create(..., external_id="foo")
function_schedules = my_function.list_schedules()
```

[CDF-3923] Add Schedules to Function SDK

---

CHANGELOG.md
cognite/experimental/data_classes/functions.py
pyproject.toml

This is due to the following change in the functions API:
https://github.com/cognitedata/context-api/pull/395

[CDF-4863] Add error to data class Function and bump to version 0.5.5

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/bad_function_code2/handler.py
tests/tests_unit/test_api/test_functions.py

Add checks to the handler checking if the file module contains a function with the correct attributes, i.e. has a function named `handle` with the correct arguments.
```
from cognite.experimental._api.functions import validate_handler_file
validate_function_folder('/path/to/handler.py/')
```

[CDF 5678] BUMP package: add checks to function folder and module

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py
tests/tests_unit/test_data_classes/test_functions.py

When the function id is present in the call, we no longer need to overload the `_load` method which enables us to use the `_list` endpoint in the APIClient in the SDK.

Incorporate function id in function call and remove `_load` method overloading

---

CHANGELOG.md
cognite/experimental/_api/entity_matching.py
pyproject.toml
tests/tests_integration/test_contextualization/test_entity_matching.py

This PR adds name, description and external-id parameter to fit for entity matcher.
It relates to https://github.com/cognitedata/context-api/pull/770

[CDF-8433] Entity matcher name, description and external-id

---

pyproject.toml

We (unstructured search) painfully discovered that mypy doesn't know types of an installed package, even when it has been typed.
This change is apparently needed, and is per [this accepted Python Enhancement Proposal](https://www.python.org/dev/peps/pep-0561/). From [mypy docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages):
> If you would like to publish a library package to a package repository (e.g. PyPI) for either internal or external use in type checking, packages that supply type information via type comments or annotations in the code should put a py.typed file in their package directory.
See also [this PR for the cognite-auth package](https://github.com/cognitedata/python-auth/pull/58) and [this PR in the main …

Add py.typed file so that mypy knows that package is typed

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

to make use of `self._retrieve_multiple` from the BaseAPI class, as we now have implemented the `functions/call_id/calls/byids` endpoint.
Is smoke tested in 
API: https://github.com/cognitedata/context-api/pull/1371
Bumps version to 0.36.0

[MLOPS-618] Changed the `FunctionCallsApi.retrieve`-method 

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

This PR introduces the possibility of specifying a `limit` in the `list`-methods of `FunctionsAPI`, `FunctionsCallAPI`, and `FunctionsScheduleAPI`. If not specified, the `limit`-default is controlled by `LIST_LIMIT_DEFAULT` and is set to 25.

[MLOPS-626] Adding `limits`-argument to `list` methods. 

---

CHANGELOG.md
cognite/experimental/data_classes/functions.py
pyproject.toml

The `function.list_schedules` method was not updated accordingly when we changed the `limit`-defaults. We now pass `limit=None` to make sure we always get every schedule associated to the relevant function.﻿

[MLOPS-679] Setting `limit=None` in `Function.list_schedules`

---

CHANGELOG.md
INTEGRATIONS&RUNS.MD
cognite/experimental/_api/integrationruns.py
cognite/experimental/data_classes/integrationruns.py
cognite/experimental/data_classes/integrations.py
pyproject.toml
tests/tests_unit/test_api/test_integrations.py
tests/tests_unit/test_api/test_runs.py

API has been updated to follow the convention of other endpoints (ie, JSON is on the form `{ "items" : [ ... ] }` with pagination). Update SDK accordingly. 
Originally from an external PR (#152), but because of limited access to api-keys in the tests it has to go through an extra branch/PR.

Change IntegrationRuns list method

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/_constants.py
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

Moves `functions/list` and `schedules/list` from `get` to `post` to allow server side filtering.
Also fixed wrong return types (e.g. `list` not pretty-printing in notebooks, before on the bottom, new on top):
Bumping version to 0.47.0

Expand functions schedules list filter

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml

As reported by @senickel on Slack: https://cognitedata.slack.com/archives/C010VCGKBCM/p1616056126005500
Bumping version to `0.48.2`

Fix missing client from _load in func.list and schedules.list

---

CHANGELOG.md
cognite/experimental/_api/functions.py
tests/tests_unit/test_api/test_functions.py

The previous error message was
```
Exactly one of id and external_id must be specified
```
but should be
```
"Exactly one of function_id and function_external_id must be specified"
```

[MLOPS-738] Fix error messages for FunctionCallsAPI

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

Must be merged after [this PR](https://github.com/cognitedata/context-api/pull/1924).

[MLOPS-736] Require function_id when creating schedule with OIDC

---

CHANGELOG.md
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_integration/test_contextualization/test_diagrams.py
tests/tests_unit/test_api/test_functions.py

To be merged after [this PR](https://github.com/cognitedata/context-api/pull/2006) in context-api.

[MLOPS-742] Add session_id field to FuncionSchedule class + release v0.57.1

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

After we disallowed setting `cpu` and `memory` on Functions in Azure ([here](https://github.com/cognitedata/context-api/pull/2085)), creating a function with the SDK in Azure stopped working. This is because these keyword arguments have default values in the SDK, and so the API returns 400. Also, setting them to `None` does not help, since we don't allow `None` in the API either.

[MLOPS-739] Modify default values of cpu and memory for Functions

---

cognite/experimental/_api/pnid_parsing.py

Slightly more precise, as `PNIDConvertResults` subclasses  `ContextualizationJob`

Update return type annotation on PNIDParsingAPI.convert

---

CONTEXTUALIZATION.md
cognite/experimental/_client.py

cleaning up anything related with unstructured search. Mark that the endpoints are also deprecated and should no longer be encouraged to use: https://docs.cognite.com/api/playground/#operation/unstructuredSearchFiles

remove unstructured

---

CHANGELOG.md
cognite/experimental/data_classes/transformation_jobs.py
cognite/experimental/data_classes/transformations.py
pyproject.toml
tests/tests_integration/test_api/test_transformations.py

`TransformationDestination.raw()` now uses `type = 'raw'` istead of `'raw_table'` and doesn't use deprecated `raw_type` parameter.

Remove unneeded raw_type parameter

---

CHANGELOG.md
cognite/experimental/data_classes/transformation_jobs.py
cognite/experimental/data_classes/transformation_notifications.py
cognite/experimental/data_classes/transformation_schedules.py
pyproject.toml
tests/tests_integration/test_api/test_transformation_jobs.py
tests/tests_integration/test_api/test_transformation_notifications.py

many transformation data classes defined `cls.cognite_client` instead of `cls._cognite_client`. This caused a circular reference exception when dumping them to json on `str(cls)`

fix data classes to string circular reference

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml

When creating a function with `function_handle` or `folder` and with `external_id` specified, the zip file uploaded to the Files API is given an external-id and is overwritten if it already exists.

[MLOPS-264] Functions: Overwrite file in filesAPI

---

tests/tests_integration/test_api/test_geospatial.py

Skipping the geospatial tests for now since the configuration on the greenfield `python-sdk-test` project is missing the necessary configuration at this moment.

Skip geospatial tests for now until configuration is ready

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
pyproject.toml

* Add optional argument metadata to FunctionsAPI.create()
* Update pyproject.toml

Add support to specify metadata when creating a function

---

CHANGELOG.md
cognite/experimental/_api/geospatial.py
pyproject.toml
tests/tests_integration/test_api/test_geospatial.py

feature external id and raster id have "free" content so we need to url encode them to avoid illegal urls (giving 404)

SBS-4823: url encode feature external id and raster id

---

cognite/experimental/_api/functions.py

The link was not displayed correctly:

Fix link in functions-docs

---

CHANGELOG.md
cognite/experimental/_api/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

Auth is removing the playgrounds endpoints in favour of v1 counterparts. 
This change is to use the new API endpoints in functions SDK

mlops-1075 Switch auth api over to v1 from playgrounds

---

CHANGELOG.md
cognite/experimental/data_classes/annotations_v2.py
pyproject.toml
tests/tests_integration/test_contextualization/test_annotations_v2.py

Adds the `data` field to AnnotationV2Filter in correspondance with the
recent changes to the AnnotationsV2 API that introduces support for
querying of the annotation data field.

VIS-789: Filter annotations by data

---

CHANGELOG.md
cognite/experimental/_api/vision.py
cognite/experimental/data_classes/annotation_types/images.py
cognite/experimental/data_classes/annotation_types/primitives.py
cognite/experimental/data_classes/vision.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_vision/test_extract.py
tests/tests_unit/test_data_classes/test_vision.py
tests/tests_unit/test_vision/test_extract.py

Also rename `annotate` -> `extract` and `annotations` to `predictions`

Fix: Make prediction results serializable

---

CHANGELOG.md
cognite/experimental/_api/extractionpipelines.py
poetry.lock
pyproject.toml

I had some issues with cognite sdk python v4, this seems to be the culprit. I'm unaware if that constructor was added for a reason..

Adjust import of ClientConfig

---

CHANGELOG.md
cognite/experimental/_api/alerts.py
poetry.lock
pyproject.toml

Update the alert's path, based on the last update in the `alert-service`, we now use `/alerts` instead of `/alerts/alerts`. 
Should be merged after [https://github.com/cognitedata/alert-service/pull/97](https://github.com/cognitedata/alert-service/pull/97).

remove redundant naming in the alert path

---

CHANGELOG.md
cognite/experimental/_client.py
poetry.lock
pyproject.toml

(v0.105.0) [CXT-778] Lock cognite-sdk to major version 4

---

CHANGELOG.md
cognite/experimental/_api/alerts.py
cognite/experimental/data_classes/alerts.py
pyproject.toml
tests/tests_integration/test_alerts/test_alerts.py

Removed unused models in the alerts api.
Deduplicate alert method is not usable, and doesn't accept correct models (throws error due to `assert_type(alerts, "alerts", [Alert, list])`).
- [ x] Changelog entry added in `CHANGELOG` or not relevant for this change
- [ x] Version updated in `pyproject.toml` or not relevant for this change

Fix deduplicated alert signature

---

CHANGELOG.md
cognite/experimental/_api/annotations.py
cognite/experimental/_api/legacy_annotations.py
cognite/experimental/_api/match_rules.py
cognite/experimental/_context_client.py
cognite/experimental/data_classes/annotations.py
cognite/experimental/data_classes/contextualization.py
cognite/experimental/data_classes/geospatial.py
cognite/experimental/utils.py
poetry.lock
pyproject.toml
tests/tests_unit/test_contextualization/test_entity_matching.py
tests/tests_unit/test_data_classes/test_annotations.py

Update and lock cognite-python-sdk version. Since this package depends on internal functions, e.g., stuff in  `cognite.client.utils._auxiliary`, it should be strictly locked. Have observed pulling this library, with a newer version of cognite-sdk than specified in the poetry.lock (but still allowed by pyproject) and getting errors because of moving / removal of these internal functions. 
Note, we should really start using a stricter linting/type-checking setup, I see a ton of unused imports, typing mismatches in my IDE. Maybe go with ruff and pyright @cognitedata/matchmakers ?

lock cognite-sdk version

---

CHANGELOG.md
pyproject.toml

need to relax the constraint as people cannot run this on newer versions of cognite-sdk
- [x ] Changelog entry added in `CHANGELOG` or not relevant for this change
- [ x] Version updated in `pyproject.toml` or not relevant for this change

Lock cognite-sdk version to major
