Jenkinsfile
cognite/experimental/_api/entity_extraction.py
pyproject.toml
tests/tests_unit/test_contextualization/test_entity_extraction.py

Addresses: https://cognitedata.atlassian.net/browse/CONTEXT-1337

Update entity extraction endpoint

---

cognite/experimental/_api/assets.py
cognite/experimental/_api/relationships.py
cognite/experimental/_client.py
cognite/experimental/_context_client.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_api/test_assets.py
tests/tests_integration/test_api/test_types.py
tests/tests_unit/test_api/test_relationships.py

prepares for using this in power sdk

Support arbitrary amount of relationship sources/targets + change assets naming

---

Jenkinsfile
tests/tests_integration/test_contextualization/test_entity_extraction.py
tests/tests_integration/test_contextualization/test_entity_matching.py
tests/tests_integration/test_contextualization/test_pnid_parsing.py
tests/tests_integration/test_contextualization/test_resource_typing.py

not ideal to ignore all these tests.. but also not ideal that jenkins just halts. I propose we use this as a baseline.

enable codecov

---

CHANGELOG.md
CONTEXTUALIZATION.md
cognite/experimental/_api/entity_extraction.py
cognite/experimental/_api/entity_matching.py
cognite/experimental/_api/pnid_parsing.py
cognite/experimental/_api/resource_typing.py
cognite/experimental/_context_client.py
cognite/experimental/data_classes/contextualization.py
cognite/experimental/exceptions.py
docs/source/cognite.rst
poetry.lock
pyproject.toml
tests/tests_integration/test_contextualization/test_entity_extraction.py
tests/tests_integration/test_contextualization/test_entity_matching.py
tests/tests_integration/test_contextualization/test_pnid_parsing.py
tests/tests_integration/test_contextualization/test_resource_typing.py
tests/tests_unit/test_contextualization/test_entity_extraction.py
tests/tests_unit/test_contextualization/test_entity_matching.py
tests/tests_unit/test_contextualization/test_pnid_parsing.py
tests/tests_unit/test_contextualization/test_resource_typing.py

moved away from asyncio, now block at the last possible moment. this may be something for functions as well

refactor context endpoints

---

poetry.lock
pyproject.toml

`typing-extensions` is a correct dependency name in PyPI

Make correct PyPI dependency

---

CHANGELOG.md
cognite/experimental/_api/assets.py
cognite/experimental/_api/labels.py
cognite/experimental/_api/types.py
cognite/experimental/_client.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/assets.py
cognite/experimental/data_classes/labels.py
cognite/experimental/data_classes/unstructured.py
pyproject.toml
tests/test_signatures.py
tests/tests_integration/test_api/test_labels.py
tests/tests_unit/test_api/test_labels.py

For the integration tests, we will need to update the api key to have labels rw capabilities.
Is that something you can do @sanderland ?

CDF-6265: add support for labels endpoint and assets labeling

---

CHANGELOG.md
docs/source/cognite.rst
pyproject.toml

Since we have some breaking changes, I guess we shoulb bump the minor version.

Release 0.9.0 + small edit in docs for function schedules

---

CHANGELOG.md
cognite/experimental/_client.py
docs/source/cognite.rst
poetry.lock
pyproject.toml

@vincent-cognite  @erlendvollset  @matiascognite  are these ok to retry?

retries and docs + lock file bump + 0.10.0

---

CHANGELOG.md
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_data_classes/test_functions.py

Now we can do:
```
function = c.functions.create(name=”func”, folder=”folder”)
while function.status in ["Queued", "Deploying"]:
function.update()
sleep(1)
```

[CDF-4730] Add update() method on Function class

---

CHANGELOG.md
cognite/experimental/_api/entity_matching.py
cognite/experimental/data_classes/contextualization.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_contextualization/test_entity_matching.py
tests/tests_unit/test_contextualization/test_entity_matching.py

This PR merges fit and fit_ml and predict and predict_ml endpoint for entity matching.

CDF-8161 Merge entity matcher endpoints

---

CHANGELOG.md
cognite/experimental/_client.py
pyproject.toml

Hopefully taking care of this error:
```
Traceback (most recent call last):
File "/src/index.py", line 28, in <module>
handle_pull_request(client.functions)
File "/src/actions.py", line 102, in handle_pull_request
function = create_and_wait_for_deployment(functions_api, function_name, external_id, file_id)
File "/src/actions.py", line 65, in create_and_wait_for_deployment
deployed = await_function_deployment(functions_api, function.external_id, wait_time_seconds)
File "/src/actions.py", line 41, in await_function_deployment
function = functions_api.retrieve(external_id=external_id)
File "/usr/local/lib/python3.8/site-packages/cognite/experimental/_api/functions.py", line 174, in retrieve
return self._retrieve_multiple(ids=id, external_ids=external_id, wrap_ids=True)
File …
```

Add retry to functions POST endpoints

---

CHANGELOG.md
cognite/experimental/data_classes/contextualization.py
pyproject.toml
tests/tests_integration/test_contextualization/test_entity_matching.py

This PR should be merged after https://github.com/cognitedata/context-api/pull/745

CDF-8264 rename refitml to refit entity matcher

---

CHANGELOG.md
cognite/experimental/_api/document_parsing.py
cognite/experimental/_api/pnid_parsing.py
cognite/experimental/_client.py
pyproject.toml
tests/tests_unit/test_contextualization/test_document_parsing.py
tests/tests_unit/test_contextualization/test_pnid_parsing.py

detect for both doc and p&id parsing, min_tokens added as a parameter

---

CHANGELOG.md
cognite/experimental/data_classes/contextualization.py
pyproject.toml
tests/tests_integration/test_contextualization/test_entity_matching.py

This PR updates retrieve so that it also outputs the model info for entity matcher models.
It solves https://cognitedata.atlassian.net/browse/CDF-8165

CDF-8165, Add model info entity matching

---

poetry.lock
pyproject.toml

ensure the fix in 2.1.1 is in due to a serious pandas regression.

bump for pandas

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

**Merge must wait** until the following PRs are merged:
https://github.com/cognitedata/context-api/pull/732
https://github.com/cognitedata/context-api-workers/pull/500

[MLOPS-487] Add customizable resources to functions and bump to v0.23.1

---

cognite/experimental/_api/entity_matching.py
cognite/experimental/_api/pnid_parsing.py

Add note about data being available.

CDF-9144 Add disclosure

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/data_classes/functions.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

Must wait until the following are merged:
https://github.com/cognitedata/context-api/pull/1194
https://github.com/cognitedata/context-api-workers/pull/775

[MLOPS-596] Add function_call_info + bump to version 0.31.1

---

CHANGELOG.md
cognite/experimental/_client.py
pyproject.toml

Added kwargs now we have all these new token args @caelyn-cognite

fix client initalization

---

CHANGELOG.md
INTEGRATIONS&RUNS.MD
cognite/experimental/data_classes/integrationruns.py
cognite/experimental/data_classes/integrations.py
pyproject.toml
tests/tests_unit/test_api/test_integrations.py
tests/tests_unit/test_api/test_runs.py

This is just a rebrand of PR #135 which was from an external consultant, and so cannot be merged directly to master since tests will be failing indefinitely on missing keys. 
The changes are to reflect a few updates to the integrations API

[CDF-10559] Update integrations and runs with new fields

---

CHANGELOG.md
cognite/experimental/_api/pnid_parsing.py
docs/source/cognite.rst
tests/tests_integration/test_contextualization/test_pnid_parsing.py
tests/tests_unit/test_contextualization/test_pnid_parsing.py

please review the latest commit in master as well, oops!

black + release

---

cognite/experimental/_api/pnid_parsing.py

From user interview we got feedback that it should be explicitly stated in the documentation that results are not written to CDF.

Add text description pnid parsing

---

cognite/experimental/data_classes/contextualization.py
docs/source/conf.py
pyproject.toml

still not even after this, not sure what's wrong

docs not showing up

---

CHANGELOG.md
INTEGRATIONS&RUNS.MD
cognite/experimental/_api/integrationruns.py
cognite/experimental/data_classes/integrationruns.py
cognite/experimental/data_classes/integrations.py
pyproject.toml
tests/tests_unit/test_api/test_integrations.py
tests/tests_unit/test_api/test_runs.py

Add add-remove functionality for list elements

[CDF-10876] Change runs list method

---

CHANGELOG.md
INTEGRATIONS&RUNS.MD
cognite/experimental/_api/integrationruns.py
cognite/experimental/data_classes/integrationruns.py
cognite/experimental/data_classes/integrations.py
pyproject.toml
tests/tests_unit/test_api/test_runs.py

Wrapping #166 since external PRs doesn't have access to secrets needed for integration tests.
Co-authored-by: AlexThunder <oleksandr.kolomiiets@cognite.com>
Co-authored-by: Mathias Lohne <mathias.lohne@cognite.com>

[CDF-11246] Add integration runs filter. Update integration entity with new fields.

---

cognite/experimental/data_classes/contextualization.py
poetry.lock
pyproject.toml
tests/tests_integration/test_contextualization/test_diagrams.py

https://github.com/cognitedata/cognite-sdk-python/pull/830
from stable sdk: in a recent update in context-api, we introduced three more statues (distributed, distributing and collecting), which breaks the current setup and test in experimental sdk, this pr introduces these statuses and refactor them as constants

Cdf 12366 update diagram

---

CHANGELOG.md
cognite/experimental/_api/transformation_schedules.py
cognite/experimental/_api/transformations.py
cognite/experimental/data_classes/transformations.py
docs/source/cognite.rst
pyproject.toml

applies pending docstring fix from #182

fix transformations data class docstring

---

CHANGELOG.md
cognite/experimental/_api/transformation_notifications.py
cognite/experimental/_api/transformation_schedules.py
cognite/experimental/_api/transformations.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/transformation_notifications.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_api/test_transformation_notifications.py

added a new client to create, list and delete transformation notifications.

transformation notifications api client and tests

---

.github/workflows/test_and_build.yml
cognite/experimental/_api/geospatial.py
cognite/experimental/_client.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/geospatial.py
tests/tests_integration/test_api/test_geospatial.py

The business objects defined are the simplest form for now. This is to get started and we can improve when our clients give us feedback.

geospatial v1 experimental support: featuretypes

---

CHANGELOG.md
cognite/experimental/_api/transformation_schema.py
cognite/experimental/_api/transformations.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/transformation_schema.py
cognite/experimental/data_classes/transformations.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_api/test_transformation_schema.py
tests/tests_integration/test_api/test_transformations.py

add a new api client to get transformations expected schema

Add transformations schema

---

CHANGELOG.md
cognite/experimental/_api/transformation_jobs.py
cognite/experimental/_api/transformations.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/transformation_jobs.py
cognite/experimental/data_classes/transformations.py
docs/source/cognite.rst
poetry.lock
pyproject.toml
tests/tests_integration/test_api/test_transformation_notifications.py
tests/tests_integration/test_api/test_transformations.py

add support to create jobs (ie. run transformations) and query them

Add transformation jobs support

---

cognite/experimental/data_classes/transformation_notifications.py

use transformation_id and transformation_external_id instead of config_id and config_external_id

fix TransformationNotificationFilter

---

CHANGELOG.md
cognite/experimental/data_classes/transformation_jobs.py
pyproject.toml
tests/tests_integration/test_api/test_transformations.py

add `TransformationJob.transformation_id` field

add transformation_id to TransformationJob

---

CHANGELOG.md
cognite/experimental/data_classes/extractionpipelines.py
pyproject.toml

Update extraction pipeline entity to remove pausing dependencies. (#197)

---

cognite/experimental/_api/geospatial.py
cognite/experimental/data_classes/geospatial.py
tests/tests_integration/test_api/test_geospatial.py

create, read, list, delete for CRSs

SBS-4018 : add support for CRS to the geospatial api client

---

cognite/experimental/_api/functions.py

Tiny stuff that doesnt warrant a new release imo. Let me know if you think otherwise

Update functions/call docs + minor cleanup

---

.github/workflows/release.yaml
.github/workflows/test_and_build.yml
tests/conftest.py
tests/tests_integration/test_api/test_geospatial.py
tests/tests_integration/test_api/test_transformation_jobs.py
tests/tests_integration/test_api/test_transformation_schedules.py
tests/tests_unit/test_api/test_functions.py

Skipping some transformations and fuctions' tests as communicated.

update github workflow to take OIDC config

---

CHANGELOG.md
cognite/experimental/data_classes/geospatial.py
pyproject.toml
tests/tests_integration/test_api/test_geospatial.py

This is not a silver bullet implementation, this would be overkill at this point.

SBS-4269 : introduce a from_geopandas() to convert geodataframes into a feature list

---

CHANGELOG.md
cognite/experimental/_api/transformation_schedules.py
cognite/experimental/_api/transformations.py
pyproject.toml

*remove is_public for schedules
*query now receives all its parameters in body

remove is_public for schedules

---

CHANGELOG.md
cognite/experimental/_api/transformation_jobs.py
cognite/experimental/_api/transformations.py
cognite/experimental/data_classes/transformation_jobs.py
pyproject.toml
tests/tests_integration/test_api/test_transformation_jobs.py
tests/tests_integration/test_contextualization/test_pnid_parsing.py

rename `transformation.job.raw_query` to `query`

Rename rawquery to query

---

CHANGELOG.md
cognite/experimental/_api/transformation_jobs.py
cognite/experimental/data_classes/transformation_jobs.py
pyproject.toml

move jobs.list filter to query params

allow list jobs by external id

---

CHANGELOG.md
cognite/experimental/_api/geospatial.py
pyproject.toml
tests/tests_integration/test_api/test_geospatial.py
tests/tests_integration/test_api/test_transformation_schedules.py
tests/tests_integration/test_api/test_transformations.py

changes after merging: https://github.com/cognitedata/coregis/pull/801

change payload sent to update feature type endpoint

---

CHANGELOG.md
cognite/experimental/_api/geospatial.py
poetry.lock
pyproject.toml

In streaming endpoint, ChunkedEncodingError happens when connection closed from server side.
Wrapping ChunkedEncodingError and ConnectionError into CogniteConnectionError so that client will catch all connection related exceptions.

coregis: handle connection close in streaming

---

tests/tests_integration/test_api/test_geospatial.py

use st prefix in within filter

---

CHANGELOG.md
poetry.lock
pyproject.toml

I also ran `poetry lock --no-update` to see if anything was out of sync.

loosen up the regex version

---

.github/PULL_REQUEST_TEMPLATE.md

I missed adding a changelog entry myself in #280, so hopefully this will prevent me and others to do the same mistake again.

Add pull request template with checklist

---

CHANGELOG.md
cognite/experimental/_api/vision.py
cognite/experimental/data_classes/vision.py
cognite/experimental/utils.py
pyproject.toml
tests/tests_unit/test_vision/test_asset_detection.py

fix(vision): certain types are not correctly converted to camelcase

---

tests/tests_integration/test_contextualization/test_annotations_v2.py
tests/utils.py

Fixing the annotation_v2 tests since the latest context-api change

Fix annotation_v2_tests

---

docs/source/cognite.rst

update geospatial documentation

---

CHANGELOG.md
cognite/experimental/_api/geospatial.py
pyproject.toml
tests/tests_integration/test_api/test_geospatial.py

implement list mvt mapping

---

docs/source/cognite.rst

add link to geospatial examples

---

CHANGELOG.md
cognite/experimental/_api/annotations_v2.py
cognite/experimental/data_classes/annotations_v2.py
pyproject.toml
tests/conftest.py
tests/tests_integration/test_contextualization/test_annotations_v2.py
tests/tests_unit/test_data_classes/test_annotations_v2.py

Not able to run the tests locally—do I need some kind of API key to do that? If they are trigged by CI here, that's probably enough. Will add the changelog and update package after I see that the test run

feat: Remove linked resource in Annotations_V2

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/_constants.py
pyproject.toml
tests/tests_unit/test_api/test_functions.py

[MLOPS-1089] Added parsing of requirements function docstring

---

CHANGELOG.md
cognite/experimental/_api/functions.py
cognite/experimental/_constants.py
pyproject.toml
tests/tests_unit/test_api/function_code_with_invalid_requirements/handler.py
tests/tests_unit/test_api/function_code_with_invalid_requirements/requirements.txt
tests/tests_unit/test_api/function_code_with_requirements/handler.py
tests/tests_unit/test_api/function_code_with_requirements/requirements.txt
tests/tests_unit/test_api/test_functions.py

[MLOPS-1160] Added validation of requirements in folder upload

---

CHANGELOG.md
cognite/experimental/data_classes/__init__.py
pyproject.toml

- [ x] Changelog entry added in `CHANGELOG` or not relevant for this change
- [ x] Version updated in `pyproject.toml` or not relevant for this change

Properly expose alerts data_classes

---

CHANGELOG.md
cognite/experimental/_api/vision.py
pyproject.toml

Also bump the version and update `CHANGELOG`

Doc: Add example to Vision's annotate method

---

CHANGELOG.md
cognite/experimental/_api/extractionpipelines.py
pyproject.toml
tests/tests_unit/test_api/test_extraction_pipelines.py

Add missing endpoints and parameters for pipeline configs

---

CHANGELOG.md
cognite/experimental/_api/vision.py
docs/source/cognite.rst
pyproject.toml

Docs: Added quickstart guide for Vision extract

---

CHANGELOG.md
cognite/experimental/_api/vision.py
cognite/experimental/data_classes/vision.py
docs/source/cognite.rst
pyproject.toml
tests/tests_integration/test_vision/test_extract.py
tests/tests_unit/test_data_classes/test_vision.py
tests/tests_unit/test_vision/test_extract.py

This work adds support for providing feature parameters to the `client.vision.extract` method.

[VIS-1040] Vision extract: parameters support

---

.github/workflows/release.yaml
.github/workflows/test_and_build.yml
CHANGELOG.md
cognite/experimental/_api/geospatial.py
poetry.lock
pyproject.toml
tests/tests_integration/test_api/test_geospatial.py

- PR title says it all 
- also matching python 3.8 as main cognite sdk does now

SBS-5407: add upsert support for geospatial

---

CHANGELOG.md
cognite/experimental/_api/alerts.py
cognite/experimental/data_classes/alerts.py
pyproject.toml
tests/tests_integration/test_alerts/test_alerts.py

Fix/Add alert tests.
Add alert deduplication endpoint.

Add deduplication

---

CHANGELOG.md
cognite/experimental/_api/simulators.py
cognite/experimental/_client.py
cognite/experimental/data_classes/__init__.py
cognite/experimental/data_classes/simulators.py
pyproject.toml
tests/tests_integration/test_alerts/test_alerts.py
tests/tests_integration/test_simulators/test_simulators.py

- [ x] Changelog entry added in `CHANGELOG` or not relevant for this change
- [ x] Version updated in `pyproject.toml` or not relevant for this change

Add simulators API

---

cognite/experimental/_api/simulators.py
cognite/experimental/data_classes/simulators.py
docs/source/cognite.rst

- added simulation runs api docs
- removed deprecated model hosting docs
it will appear here: https://cognite-sdk-experimental.readthedocs-hosted.com/en/latest/cognite.html#cogniteclient

Add simulator runs docs
